import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/zandercpzed/smartwrite-orchestrator
*/
`;

const prod = (process.argv[2] === "production");

// Optional: auto-deploy to local Obsidian vault during dev
// Set OBSIDIAN_PLUGIN_PATH in your env to enable
const OBSIDIAN_PLUGIN_PATH = process.env.OBSIDIAN_PLUGIN_PATH;

const copyToObsidian = () => {
	if (!OBSIDIAN_PLUGIN_PATH || !fs.existsSync(OBSIDIAN_PLUGIN_PATH)) {
		if (OBSIDIAN_PLUGIN_PATH) {
			console.log(`OBSIDIAN_PLUGIN_PATH "${OBSIDIAN_PLUGIN_PATH}" not found, skipping copy.`);
		}
		return;
	}
	try {
		fs.copyFileSync("main.js", path.join(OBSIDIAN_PLUGIN_PATH, "main.js"));
		fs.copyFileSync("manifest.json", path.join(OBSIDIAN_PLUGIN_PATH, "manifest.json"));
		if (fs.existsSync("styles.css")) {
			fs.copyFileSync("styles.css", path.join(OBSIDIAN_PLUGIN_PATH, "styles.css"));
		}
		console.log("✅ Plugin deployed to Obsidian vault.");
	} catch (err) {
		console.error("❌ Failed to copy to Obsidian:", err.message);
	}
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	copyToObsidian();
	process.exit(0);
} else {
	await context.watch();
}
